### ISSUE TITLE
fspath requires trailing slash

### ISSUE THREAD

**Issue by carltongibson** [scripting/river4#4]
I used back ticks to set my `fspath` environment variable...

     export fspath=`pwd`

This results in a path without a trailing slash, something like...

    /Users/davewiner/river4data

Running with such a path results in an error:

```
river4.js:1216
		for (var i = 0; i < list.length; i++) {
		                        ^
TypeError: Cannot read property 'length' of undefined
    at .../river4/river4.js:1216:27
    at Object.oncomplete (fs.js:107:15)
````

I've not dug in but I'm guessing the path to the lists dir is generated something like: `fspath + "lists"`. 

Better would be to use [`path.join`](http://nodejs.org/api/path.html#path_path_join_path1_path2).

**Comment by carltongibson** [comment]
Closing this to clear up my console. Presume you have it covered. (Would fix and PR but toolchain is a little opaque.)
